# Generated by Django 4.2.10 on 2024-09-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskstodo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
